### ISSUE TITLE
How long to get fully trained?

### ISSUE THREAD

**Issue by gxwangupc** [3DOM-FBK/HyRe#1]
Hi, I'd like to know what GPUs you used and how long did it take to train on each dataset.

**Comment by mwelponer** [comment]
Dear Guangxing, according to your question I guess you believe this code makes use of some neural network to process the data, while this is not the case. My algorithm simply takes as input the photogrammetrically computed point cloud as well as the lidar one and gives you in output the corresponding "aligned" pointcloud. The alignment makes use of the points properties information (subdivision into classes) and the subdivision of the 3D space into a grid (the voxels) to  drive the alignment, according to the need. 
We have processed our data on a common Intel multicore CPU.
Any more doubt, feel free to make a new question,
cheers

**Comment by gxwangupc** [comment]
Thank you very much.
